# Generated by Django 5.1.4 on 2025-01-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='date',
            new_name='Адрес_проживания',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='name',
            new_name='Регистрационный_талон',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='language',
            new_name='Регистрация',
        ),
        migrations.RenameField(
            model_name='certificate',
            old_name='subject',
            new_name='Статус_регистрации',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='centre_no1',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='centre_no2',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='level',
        ),
        migrations.AddField(
            model_name='certificate',
            name='Дата_рождения',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='Имя',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='Номер_паспорта',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='Отчество',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='Регистрация_по',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='Страна_паспорта',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='certificate',
            name='Фамилия',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
